### ISSUE TITLE
Using a better approximation

### ISSUE THREAD

**Issue by xmodar** [howion/lambert-w-function#6]
The implemented method doesn't approximate the function really well. One might consider using [this implementation](https://gist.github.com/xmodar/baa392fc2bec447d10c2c20bbdcaf687) instead. We are working on the log scale to avoid overflow issues. Sorry, I am too lazy to create a pull request 😅

**Comment by howion** [comment]
Hi, thank you very much for the implementation. I didn't realize this library was being used. So, after reading and testing the given implementation, I did add the implementation as the default. For the previous iterated implementation which is no longer the default, I have added the support for values less than E.
